# Generated by Django 5.2.13 on 2026-04-28 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='base_transit_hours',
            field=models.FloatField(default=24.0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='cost_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='risk_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='weathersnapshot',
            name='condition',
            field=models.CharField(choices=[('clear', 'Clear'), ('rain', 'Rain'), ('storm', 'Storm'), ('fog', 'Fog'), ('unknown', 'Unknown')], max_length=20),
        ),
        migrations.CreateModel(
            name='TrafficSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congestion', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unknown', 'Unknown')], max_length=20)),
                ('score', models.FloatField(default=0.2)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traffic', to='tower.location')),
            ],
        ),
    ]
