# Generated by Django 5.2.13 on 2026-04-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower', '0002_shipment_base_transit_hours_shipment_cost_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='budget_usd',
            field=models.PositiveIntegerField(default=2500),
        ),
        migrations.AddField(
            model_name='shipment',
            name='expected_profit_usd',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
