# Generated by Django 5.0.14 on 2026-04-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower', '0004_company_shipment_created_by_shipment_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='ai_explained_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='ai_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
